### ISSUE TITLE
Port everything to C++ and use Vulkan

### ISSUE THREAD

**Issue by native-m** [shaderboi/tempeh-engine#1]
_**it's a must**_

![FB_IMG_16255486475008027.jpg](https://user-images.githubusercontent.com/14961870/128770110-6efc828d-73f2-4985-9ff1-1078a8e72911.jpg)

**Comment by andraantariksa** [comment]
![](https://en.meming.world/images/en/thumb/1/1d/Creating_Bugs_Bunny%27s_%22No%22.jpg/300px-Creating_Bugs_Bunny%27s_%22No%22.jpg)
